Algoritmo "ConteAte0"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 17/02/2024
Var
   contador:inteiro


Inicio
   contador <- 10
   enquanto (contador >= 0) faca
      escreval (contador)
      contador <- contador - 1
   FimEnquanto
   Escreval("terminei de contar")


Fimalgoritmo