Algoritmo "ParOuImpar"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 14/02/2024
Var
   N: inteiro

Inicio
   Escreva("Digite um némro qualquer: ")
   Leia(N)
   Se (N % 2 = 0) entao
      Escreval("O número ", N, " é PAR")
   Senao
      Escreval("O número ", N, " é IMPAR")
   FimSe

Fimalgoritmo